#!/bin/bash
dos2unix dominion.c
dos2unix dominion.h
dos2unix dominion_helpers.h
dos2unix interface.c
dos2unix interface.h
dos2unix playdom.c
dos2unix player.c
dos2unix rngs.c
dos2unix rngs.h
dos2unix rt.c
dos2unix unittest1.c
dos2unix unittest2.c
dos2unix unittest3.c
dos2unix unittest4.c
dos2unix unittest5.c
dos2unix unittest6.c
dos2unix unittest7.c
dos2unix unittest8.c
dos2unix unittest9.c
dos2unix unittest10.c

